### PR TITLE
Make imports Clojure 1.10 compatible in version 3.0.x

### PR DESCRIPTION
**Pull request by Jarzka**
Relates: https://github.com/clojurewerkz/elastisch/issues/266

### CODE REVIEW

**Comment by Jarzka** [comment]
Fixed.

**Comment by Jarzka** [comment]
Fixed one more time. :D

**Comment by Jarzka** [comment]
Any news on the update?

**Comment by michaelklishin** [comment]
No updates. Producing a release is not particularly time consuming. Reviewing and updating all docs is (and I keep dropping the ball on it, obviously).

**Pull request merged**
