### PR TITLE
Adds support for nested aggregations with the native driver for date_histogram, date_range, histogram, range and terms

### PR DESCRIPTION
**Pull request by mitchelkuijpers**
Adds support for nested aggs, also updated the tests to test the new capabilities.

### CODE REVIEW

**Comment by michaelklishin** [comment]
:+1:

**Comment by michaelklishin** [comment]
@mitchelkuijpers please update `ChangeLog.md` and credit yourself there!

**Comment by mitchelkuijpers** [comment]
Thnx I will! Btw I saw I accidentally created some deftests with the same name. So another pull request is coming your way

**Comment by mitchelkuijpers** [comment]
@michaelklishin I need to add another header in the sense of Changes between Elastisch 2.1.0-beta9 and 2.1.0. What will be the next first version Elastisch 2.2.0-beta1?

**Comment by michaelklishin** [comment]
`2.2.0-beta1` or `2.2.0` are both OK.

**Pull request merged**
