### PR TITLE
Allow default HTTP options to be overridden

### PR DESCRIPTION
**Pull request by MerelyAPseudonym**
I believe these changes address [#198](https://github.com/clojurewerkz/elastisch/issues/198).

If you have any suggestions or requests, just let me know. I'm open to feedback.

### CODE REVIEW

**Comment by MerelyAPseudonym** [comment]
Also, I'm fine with backing out the spacing commits ([1042159](https://github.com/MerelyAPseudonym/elastisch/commit/10421599afae1ca31b076d8b52edbefb1b881f85) and [c5a21c5](https://github.com/MerelyAPseudonym/elastisch/commit/c5a21c5b0b6c750984fc5d97586a4b9ade8f5624)) or squashing them. As the bodies of the messages say, I made those changes to make the diff of [the **main** commit](https://github.com/clojurewerkz/elastisch/commit/654e8cfd4d5151b543d576783191c7397b9213ec) clearer.

**Comment by michaelklishin** [comment]
@MerelyAPseudonym I've cherry-picked a couple of commits to `2.2.x-stable`, please rebase (there are conflicts).

**Comment by michaelklishin** [comment]
OK, so this clashes with #199. I'm happy to consider this change because it seems to be more generic in nature.

**Comment by MerelyAPseudonym** [comment]
@michaelklishin I'm happy to rebase the changes. I'll probably get to it later today.

**Comment by MerelyAPseudonym** [comment]
@michaelklishin Finally got to it! Sorry for the delay.

**Comment by MerelyAPseudonym** [comment]
@michaelklishin I noticed that the build was failing, so I fixed the problem and rebased.

As before, please let me know if you have any suggestions or requests.

**Comment by michaelklishin** [comment]
@MerelyAPseudonym thank you. Can you please submit the same change against `master`?

**Comment by MerelyAPseudonym** [comment]
@michaelklishin Will do.

**Pull request merged**
